FROM node:14 AS development

WORKDIR /src/app

COPY package*.json ./

RUN npm install

COPY . .

#RUN npm run build

FROM node:14 AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /src/app

COPY --from=development /src/app/ .

EXPOSE ${SERVICE_DB_PORT}

CMD [ "node", "dist/main" ]



# Example Commands to build and run the dockerfile
# docker build -t thomas-nest .
# docker run thomas-nest