version: "3.8"
services:
  front:
    build: ./frontend
    environment: 
      PORT: ${FRONT_PORT}
    ports:
      - "${FRONT_HOST}:${FRONT_PORT}"
    networks:
      - frontend
      
  api:
    build:
      dockerfile: Dockerfile
      context: ./api-gateway
      target: development
    volumes:
      - ./api-gateway/src/:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:debug  
    environment: 
      NODE_ENV: development
      PORT: ${API_GATEWAY_PORT}
    ports:
      - "${API_HOST}:${API_GATEWAY_PORT}"
    networks:
      - frontend
      - backend

  service-a:
    build:
      dockerfile: Dockerfile
      context: ./service-a
      target: development
    volumes:
      - ./api-gateway/src/:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:debug
    environment: 
      NODE_ENV: development
      PORT: ${SERVICE_A_PORT}
    ports:
      - "${SERVICE_A_PORT}:${SERVICE_A_PORT}"
    networks:
      - backend
#-----------------DB-----------------#
  service-db:
    build:
      context: ./service-database
      target: development
    volumes:
      - ./service-database/src/:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:debug
    environment: 
      NODE_ENV: development
      PORT: ${SERVICE_DB_PORT}
      MYSQL_HOST: mysqldb
      MYSQL_DATABASE: nest
    ports:
      - "${SERVICE_DB_PORT}:${SERVICE_DB_PORT}"
    networks:
      - mysql
      - backend
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "nest"
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
       - ${LOCAL_DOCKER_VOLUMES}:/var/lib/mysql
    networks:
      - mysql

  adminer:
    image: adminer
    ports:
      - ${DB_HOST}:8080
    networks:
      - mysql

networks: 
  mysql:
    driver: bridge
  backend:
    driver : bridge
  frontend:
    driver : bridge